### ISSUE TITLE
FinViz Fundamentals

### ISSUE THREAD

**Issue by dubleigh** [mariostoev/finviz#124]
Hello,
It seem as if the FinViz fundamentals endpoint has lost functionality, is there a replacement?

Here is some old code:

    from finvizfinance.quote import finvizfinance
    stock = finvizfinance(ticker)
    stock_fundamentals = stock.TickerFundament()
    print(stock_fundamentals)

Thank you!

**Comment by d3an** [comment]
First off I just want to say that this issue is for a different package entirely! 🤣 🤣 

But in the spirit of collaboration, your problem is that `TickerFundament()` is not a valid method under the [`finvizfinance`](https://github.com/lit26/finvizfinance) package. If it used to work, then its likely the package's owner/maintainer made breaking changes without notifying users. The correct method is now `ticker_fundament()`.

So, the replacement code is:
```python
from finvizfinance.quote import finvizfinance
stock = finvizfinance(ticker)
stock_fundamentals = stock.ticker_fundament()
print(stock_fundamentals)
```

**Comment by dubleigh** [comment]
You sir, get a gold star. Thank you for the feedback!

(And yes, I will post on the correct repo next time lol)
