### ISSUE TITLE
stock_list.get_charts returning 0 byte image files

### ISSUE THREAD

**Issue by windowshopr** [mariostoev/finviz#23]
Love the tool!

Noticed that when I use the function:

`stock_list.get_charts(period='d', chart_type='c', size='l', ta=True)`

...I get a bunch of empty/nothing .jpg files in the newly created charts folder? I've tried using 'm' and both True and False for ta, still the same. I also tried changing the .jpg to .jpeg (just in case) in the scraper_functions.py file too. Don't know if it matters, but I'm running Windows 10, Python 3.6. Any ideas on things to try? Thanks!

**Comment by tkifelew** [comment]
I am also having the same issue. I will look for workarounds in the upcoming weeks.

**Comment by mariostoev** [comment]
Maybe FinViz has changed the image type from .jpg to .png. That might cause the problem since I tried replicating the code to see if the URL's are actually valid and it worked. 

example[https://finviz.com/chart.ashx?t=AAPL&ty=c&ta=0&p=d&s=l](url) `(period='d', chart_type='c', size='l', ta=True)`

@tkifelew try changing the file name from .jpg to .png in the method download_chart_image inside scraper_functions[https://github.com/mariostoev/finviz/blob/d0c9fc61f994f0cea203a751a7482feab1e4ad1c/finviz/helper_functions/scraper_functions.py#L64](url)

**Comment by mariostoev** [comment]
Accidentally closed, my bad.

**Comment by tkifelew** [comment]
Changed .jpg to .png and the .png files are all blank 0KB still. Could finviz have changed the image locations or something?
![image](https://user-images.githubusercontent.com/32316442/69175864-6b153180-0ab9-11ea-885d-b642a8e390c2.png)
![image](https://user-images.githubusercontent.com/32316442/69176227-348be680-0aba-11ea-8e99-38bb5b1c943c.png)

**Comment by mariostoev** [comment]
Hey @windowshopr, @tkifelew,

I reviewed the issue and seems that there's a mistake in the documentation. The simple fix is to use '1' or '0' for technical analysis, instead of True and False. I will change the README and the documentation inside the code.

Thank you for the contribution!

**Comment by tkifelew** [comment]
I noticed the doc error through docstrings I have ta='1'. I changed download_image back to .jpg still I get 0kb images, Could you test if your getting images on your end?

**Comment by mariostoev** [comment]
get_stock_charts method is returning 0kb images again. Can someone look into that?

**Comment by mariostoev** [comment]
I believe the issue is not in the code, since calling the method with different parameters sometimes generates link that does not exist.

For example:
`stocks = Screener(tickers=['AAPL'])`
`stocks.get_charts(period='m', chart_type='c', size='l', ta='1')`

This code tries to access [this](https://finviz.com/chart.ashx?ty=c&ta=1&p=m&s=l&t=AAPL), which does not exist because finviz does not support these type of chart with the exact parameters. Do not think of it as an interactive chart that can have any type of combination like period, chart type, size and ta. It is a static imagine and only certain combinations are possible. Such as: 

`stocks = Screener(tickers=['AAPL'])`
`stocks.get_charts(period='m', chart_type='c', size='l', ta='0')`

This works and I get: 

![image](https://user-images.githubusercontent.com/21347113/71321365-ef940f00-24c0-11ea-9333-18553409bc6b.png)

Can someone test this and come back to me? Thanks. 

@tkifelew 
@windowshopr 
@Maiakel

**Comment by Maiakel** [comment]
Yes this worked for me thanks

**Comment by mariostoev** [comment]
Issue closed.
