### ISSUE TITLE
15 minute delay question

### ISSUE THREAD

**Issue by arthurcolle** [mariostoev/finviz#28]
The FinViz site seems to indicate that "real-time" quotes are in fact possible if you buy their premium subscription. Your description says that theres a 15 minute delay without any qualification.

Can you confirm that with a premium subscription, there is still a 15 minute delay?

**Comment by mariostoev** [comment]
Hello @arthurcolle,

As far as I know the premium subscription does not change the layout of the website. If the HTML/CSS remains the same the scraper should work just fine. Also, I remember someone emailing me asking the same question but he didn't follow up, so maybe you can try it out and respond if it worked. Then you can add it to the README so people don't wonder anymore!

Thank you!

**Comment by mariostoev** [comment]
Oh, this did not answer your question. 

I think with the premium version the screener should work and display almost realtime data. Keep in mind that it takes roughly 30 seconds to scrape all tickers so you will have 30 second delay on SOME of the the prices (this is due to the asynchronous nature of the code). If you have any more questions feel free to email me or open new issue!

If you try out the premium version, tell us if everything works and open a pull request.

Thanks again.

**Comment by arthurcolle** [comment]
I’ll submit a PR whenever its done to uplift this library to actually properly support premium accounts. I popped for the year subscription so hopefully I’ll be able to get it done before then ;)

What I mean by properly support is that: 

Right now you only really support “logins” for portfolios, is this correct? What would be needed is to login first, and then scrape from the actual logged in browser instance. Do you think I’d be able to write this without bringing in Selenium? Maybe this already uses Selenium but I haven’t checked yet. Just wanted to discuss with you a bit before diving in to a new development effort.

Cheers
