### ISSUE TITLE
Cannot connect to host finviz.com:443

### ISSUE THREAD

**Issue by parker-moore** [mariostoev/finviz#39]
First for loop 'exch_nyse' works - but 'exch-nasd' does not? Can anyone else connect using 'exch-nasd' as a filter?

Exception has occurred: ClientConnectorError
Cannot connect to host finviz.com:443 ssl:default [The semaphore timeout period has expired]

def getTickers(price,marketcap):
    df = pd.DataFrame()
    for exchange in ['exch_nyse','exch_nasd']:
        filters = [price,marketcap,exchange]
        stock_list = pd.DataFrame(Screener(filters=filters).data)

**Comment by mariostoev** [comment]
The main reason of this error is that the Windows does not retry the network connection and it is timed out. The reason for network problem might be because of weak signals or slow wired links or a faulty network adapter driver. This is the case when problem occurs while scraping over a network. 

Hence, the issue is on your end and we can't really fix it. 

ps: I tried the same exact code and it worked for me.
