### ISSUE TITLE
Support for Groups

### ISSUE THREAD

**Issue by KirilNN** [mariostoev/finviz#43]
First of all congrats on the great work you are doing. I wanted to ask you do you plan to support FinViz groups API? What I mean is shown here:

https://finviz.com/groups.ashx?g=sector&v=120&o=pe

Thanks a keep up!

**Comment by mariostoev** [comment]
Thank you @KirilNN, 

Currently the library does not support FinViz Groups, however, I will look into writing the code for it, since it's not much different than the Screener web page. For now, what you can do is use the Screener to filter companies in a specific sector/industry and then run a for loop to calculate total market cap or average P/E ratio (for example).  

Finally, I have added your suggestion the the main project board so anyone who wants can start working on it.
